name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CDK
        run: npm i -g aws-cdk
      - name: Install jenkins-master
        run: npm ci
        working-directory: jenkins-master
      - name: Test jenkins-master
        run: cdk synth
        working-directory: jenkins-master
      - name: Install jenkins-kaniko
        run: npm ci
        working-directory: jenkins-kaniko
      - name: Test jenkins-kaniko
        run: cdk synth
        working-directory: jenkins-kaniko
